### ISSUE TITLE
ModuleNotFoundError: No module named 'barez'

### ISSUE THREAD

**Issue by ddongmogi** [phamquiluan/publaynet#14]
While training with PubLayNet dataset, I found following error:

```
 [May-10 13:04] [CRITICAL] No module named 'barez'  <__main__, <module>(): 563>
Traceback (most recent call last):
  File "main_publaynet.py", line 557, in <module>
    main(args)
  File "main_publaynet.py", line 230, in main
    main_worker(0, ngpus_per_node, args)
  File "main_publaynet.py", line 394, in main_worker
    args=args
  File "main_publaynet.py", line 479, in train_one_epoch
    from barez import overlay_ann
ModuleNotFoundError: No module named 'barez'
```

So I use ``` pip install barez ```, but I have ```ERROR: No matching distribution found for barez```

I installed all modules in 'requirement.txt'. 
I searched on google, but couldn't find a related solution. How can I solve it?

Thank you.

+ I use torch 1.5.1

**Comment by phamquiluan** [comment]
remove that barez, it is unnecessary

**Comment by ddongmogi** [comment]
However, the ```overlay_ann``` function is being used in the code. Doesn't it need this code too?

```
from barez import overlay_ann
...
image = overlay_ann(image, m, box, "", score)
```

**Comment by phamquiluan** [comment]
it is unnecessary also @ddongmogi

**Comment by ddongmogi** [comment]
@phamquiluan thank you for the advice. It works well !!
